name: publish
on: [push]
jobs:
  publish-keycloak-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Keycloak Docker image with RabbitMQ event publisher SPI
        run: |
          docker build . --tag ghcr.io/tpb1908/kc-with-spi:latest
          docker run ghcr.io/tpb1908/kc-with-spi:latest
          docker push ghcr.io/tpb1908/kc-with-spi:latest
